# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googleFacebookLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for googleFacebookLogin
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit' 


  target 'googleFacebookLogin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'googleFacebookLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'googleFacebookLogin-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for googleFacebookLogin-tvOS


end
